# fly.toml app configuration file generated for zachsbot-discord on 2023-08-20T15:22:05-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zachsbot-discord"
primary_region = "sea"

[env]
RUST_LOG = "info"
